<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Palimpseste.Storage\Palimpseste.Storage.csproj" />
    <ProjectReference Include="..\..\shared\Palimpseste.Core\Palimpseste.Core.csproj" />
  </ItemGroup>

</Project>
