#!/usr/bin/env python3
"""Deterministic design-case checks for a *new* A response; no model calls.

Usage: python tests/calibration/check_prompt_a.py --description <new-A.json>
       python tests/calibration/check_prompt_a.py --self-test

Passing here is only a structural screen. It is not an artistic verdict or a
claim that this response was generated by Luna.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import jsonschema


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CASE = Path(__file__).parent / "design" / "lava-laser-001.json"
SCHEMA = ROOT / "contracts" / "spell-description.schema.json"


def unique_object(pairs: list[tuple[str, object]]) -> dict:
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique_object)
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def check(case: dict, description: dict, schema: dict) -> list[str]:
    issues: list[str] = []
    validator = jsonschema.Draft202012Validator(schema)
    schema_issues = sorted(validator.iter_errors(description), key=lambda issue: str(issue.path))
    if schema_issues:
        return [f"schema: {issue.message}" for issue in schema_issues]

    observations = {item["id"] for item in description["observations"]}
    if len(observations) != len(description["observations"]):
        issues.append("observation IDs are not unique")
    clauses = description["clauses"]
    if len({item["id"] for item in clauses}) != len(clauses):
        issues.append("clause IDs are not unique")
    for clause in clauses:
        if not set(clause["observation_ids"]).issubset(observations):
            issues.append(f"clause {clause['id']} cites an absent observation")

    expected = case["structural_expectations"]
    forbidden_dimensions = set(expected.get("forbidden_fact_dimensions", []))
    forbidden_events = set(expected.get("forbidden_event_values", []))
    for clause in clauses:
        for fact in clause["facts"]:
            if fact["dimension"] in forbidden_dimensions or (
                fact["dimension"] == "event" and fact["value"] in forbidden_events
            ):
                issues.append(
                    f"clause {clause['id']} has unsupported {fact['dimension']}={fact['value']} "
                    "for this single-stroke design case"
                )

    mechanical = [clause for clause in clauses if clause["kind"] == "mechanical"]
    facts_by_subject: dict[str, set[tuple[str, str]]] = {}
    for clause in mechanical:
        facts_by_subject.setdefault(clause["subject_id"], set()).update(
            (fact["dimension"], fact["value"]) for fact in clause["facts"]
        )
    primary_subjects = [
        subject for subject, facts in facts_by_subject.items()
        if ("carrier", expected["primary_carrier"]) in facts
    ]
    if len(primary_subjects) != 1:
        issues.append("exactly one mechanical primary beam subject is required")
        return issues

    subject = primary_subjects[0]
    facts = facts_by_subject[subject]
    if len(facts_by_subject) != expected["subject_count"]:
        issues.append(f"expected {expected['subject_count']} mechanical subject")
    if ("affinity", expected["primary_affinity"]) not in facts:
        issues.append(f"primary subject lacks affinity={expected['primary_affinity']}")
    if len(description["relations"]) != expected["relation_count"]:
        issues.append("the one-direction case has an unrequested relation")
    shapes = [shape for shape in description["shape_requests"] if shape["subject_id"] == subject]
    if not any(shape["role"] == expected["primary_shape_role"] for shape in shapes):
        issues.append("primary beam does not request a path from the drawing")
    return issues


def self_test(case: dict, schema: dict) -> None:
    valid = {
        "schema_version": "sp.description/1.0",
        "title": "Fixture de contrôle",
        "summary": "Fixture synthétique de vérification du contrôle, pas une sortie de Luna.",
        "observations": [{"id": "o1", "region": "ring", "visible_feature": "Trait continu.",
                          "interpretation": "Emission linéaire."}],
        "clauses": [{"id": "c1", "subject_id": "s0", "kind": "mechanical",
                     "text": "Faisceau de feu.", "observation_ids": ["o1"],
                     "facts": [{"dimension": "carrier", "value": "beam"},
                               {"dimension": "affinity", "value": "fire"}]}],
        "relations": [],
        "shape_requests": [{"subject_id": "s0", "region": "ring", "role": "path"}],
    }
    assert check(case, valid, schema) == [], "positive checker fixture failed"
    for dimension in ("carrier", "affinity"):
        changed = json.loads(json.dumps(valid))
        changed["clauses"][0]["facts"] = [
            fact for fact in changed["clauses"][0]["facts"] if fact["dimension"] != dimension
        ]
        assert check(case, changed, schema), f"missing {dimension} escaped the checker"
    changed = json.loads(json.dumps(valid))
    changed["clauses"][0]["kind"] = "visual_only"
    assert check(case, changed, schema), "visual-only response escaped the checker"
    changed = json.loads(json.dumps(valid))
    changed["shape_requests"][0]["role"] = "silhouette"
    assert check(case, changed, schema), "missing path escaped the checker"
    for dimension, value in (("effect", "damage"), ("target", "hostile"), ("event", "hit")):
        changed = json.loads(json.dumps(valid))
        changed["clauses"][0]["facts"].append({"dimension": dimension, "value": value})
        assert any("unsupported" in issue for issue in check(case, changed, schema)), (
            f"unsupported {dimension} escaped the checker"
        )
    changed = json.loads(json.dumps(valid))
    changed["clauses"].append({"id": "c2", "subject_id": "s0", "kind": "visual_only",
                               "text": "Fixture secondaire.", "observation_ids": ["o1"],
                               "facts": [{"dimension": "effect", "value": "burn"}]})
    assert any("unsupported" in issue for issue in check(case, changed, schema)), (
        "unsupported fact in a second clause escaped the checker"
    )
    print("calibration_checker_self_test=pass (synthetic checker fixtures only)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", type=Path, default=DEFAULT_CASE)
    parser.add_argument("--description", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    case, schema = load_json(args.case), load_json(SCHEMA)
    if args.self_test:
        self_test(case, schema)
    if args.description:
        issues = check(case, load_json(args.description), schema)
        for issue in issues:
            print("FAIL:", issue)
        if issues:
            return 1
        print("structural_screen=pass; human image/text/cast review still required")
    if not args.self_test and not args.description:
        parser.error("provide --description and/or --self-test")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
